revoltchat/backend

src/database/entities/channel.rs, src/database/entities/server.rs, src/routes/channels/channel_edit.rs, src/routes/channels/group_create.rs, src/routes/servers/channel_create.rs, src/routes/servers/server_create.rs, src/routes/servers/server_edit.rs
=> Add nsfw to channel and server

Cargo.lock, Cargo.toml, src/notifications/websocket.rs
=> Add msgpack to the websocket

src/database/entities/microservice/january.rs
closes https://github.com/revoltchat/delta/issues/61
=> color -> colour

src/database/entities/message.rs, src/database/entities/microservice/autumn.rs
closes https://github.com/revoltchat/delta/issues/14
=> Generate Web Push notifications on server.

src/database/entities/channel.rs, src/database/entities/message.rs, src/routes/channels/group_create.rs, src/routes/servers/channel_create.rs, src/routes/servers/server_create.rs, src/routes/users/open_dm.rs
closes https://github.com/revoltchat/delta/issues/55
=> Unify last_message field to always be just an ID

.github/workflows/rust.yaml
closes https://github.com/revoltchat/delta/issues/75
=> Setup gh actions and provide unit tests

.github/workflows/docker.yml, Cargo.lock, Cargo.toml, src/notifications/websocket.rs
- fixed enums to be the string version
- encode messages from events
=> fix msgpack encoding

Cargo.lock, Cargo.toml, src/main.rs, src/routes/channels/message_send.rs, src/routes/root.rs, src/util/ratelimit.rs, src/util/result.rs
this pr uses a fixed window rate limit system, currently sending messages is 10 per 10 secs and the rest of the endpoints have not been done
=> add ratelimits

src/routes/servers/server_edit.rs
=> fix: uploading server banners was broken

crates/delta/src/routes/customisation/emoji_create.rs
=> fix: set the cap to 100

crates/delta/src/routes/push/subscribe.rs, crates/delta/src/routes/push/unsubscribe.rs, crates/quark/src/events/impl.rs, crates/quark/src/permissions/defn/mod.rs, crates/quark/src/presence/mod.rs, crates/quark/src/tasks/process_embeds.rs
The changes made effectively have no difference in testing compared to the original (as is intended for clippy), the purpose of this pr is to remove annoying warnings on compile time.
=> chore: remove clippy warnings

crates/quark/src/permissions/defn/permission.rs
=> feat: enable reactions by default in servers/DMs

Cargo.lock, crates/bonfire/Cargo.toml, crates/delta/Cargo.toml, crates/delta/src/routes/mod.rs, crates/delta/src/routes/safety/mod.rs, crates/delta/src/routes/safety/report_content.rs, crates/quark/Cargo.toml, crates/quark/src/impl/dummy/mod.rs, crates/quark/src/impl/dummy/safety/report.rs, crates/quark/src/impl/dummy/safety/snapshot.rs, crates/quark/src/impl/mongo/mod.rs, crates/quark/src/impl/mongo/safety/report.rs, crates/quark/src/impl/mongo/safety/snapshot.rs, crates/quark/src/models/mod.rs, crates/quark/src/models/safety/report.rs, crates/quark/src/models/safety/snapshot.rs, crates/quark/src/traits/mod.rs, crates/quark/src/traits/safety/report.rs, crates/quark/src/traits/safety/snapshot.rs, crates/quark/src/util/result.rs, crates/quark/src/web/ratelimiter.rs
=> feat: user safety API

Cargo.lock, crates/delta/Cargo.toml, crates/delta/src/main.rs, crates/delta/src/routes/channels/message_send.rs, crates/quark/Cargo.toml, crates/quark/src/impl/generic/channels/channel_invite.rs, crates/quark/src/impl/generic/media/emoji.rs, crates/quark/src/impl/mongo/admin/migrations/scripts.rs, crates/quark/src/impl/mongo/users/user.rs, crates/quark/src/lib.rs, crates/quark/src/permissions/defn/permission.rs, crates/quark/src/permissions/impl/permission.rs, crates/quark/src/presence/entry.rs, crates/quark/src/tasks/ack.rs, crates/quark/src/tasks/last_message_id.rs, crates/quark/src/tasks/process_embeds.rs, crates/quark/src/tasks/web_push.rs, crates/quark/src/types/january.rs, crates/quark/src/util/variables/delta.rs, crates/quark/src/web/idempotency.rs, crates/quark/src/web/ratelimiter.rs
=> chore: move to once_cell from lazy_static

.github/workflows/docker.yaml, Dockerfile, crates/bonfire/Dockerfile, crates/delta/Dockerfile, scripts/build-image-layer.sh
---
Hello! I've got a preliminary cross-compilation (`amd64`/`arm64`) setup going with the `base`, `bonfire`, and `delta` container images here. Testing has been a bit wonky, but all six images are building on my local M1 machine.
With cross compilation, `buildx` of `base` for both platforms takes about **10 minutes** for me vs **???** with emulation 😄.
I plan to create a separate branch and try triggering some build and push Actions on my fork, but wanted to get the work out there sooner for comment in case my removal of `cargo install` in the separate service images was going to cause problems.
✌️
=> cross compile arm64 / amd64 images

crates/delta/src/routes/servers/invites_fetch.rs
=> fix: remove check for bot account fetching invites from a server

crates/quark/src/util/variables/delta.rs
=> chore: bump max bots count to 10

crates/delta/src/routes/channels/members_fetch.rs
=>  removed check for bot account under group member fetch

crates/delta/src/routes/channels/message_edit.rs, crates/delta/src/routes/channels/message_send.rs, crates/delta/src/routes/webhooks/webhook_execute_github.rs, crates/quark/src/impl/generic/channels/channel.rs, crates/quark/src/impl/generic/channels/message.rs, crates/quark/src/models/channels/message.rs, crates/quark/src/util/result.rs
=> fix: send message route not accepting null

Cargo.lock, crates/core/database/Cargo.toml, crates/core/database/src/models/admin_migrations/ops/mongodb/init.rs, crates/core/database/src/models/admin_migrations/ops/mongodb/scripts.rs, crates/core/database/src/models/users/model.rs, crates/core/database/src/util/bridge/v0.rs, crates/core/models/src/v0/users.rs, crates/delta/src/routes/bots/create.rs, crates/delta/src/routes/bots/edit.rs, crates/delta/src/routes/onboard/complete.rs, crates/delta/src/routes/users/edit_user.rs, crates/delta/src/routes/users/send_friend_request.rs, crates/delta/src/util/regex.rs, crates/quark/src/impl/dummy/users/user.rs, crates/quark/src/impl/generic/users/user.rs, crates/quark/src/impl/mongo/users/user.rs, crates/quark/src/models/users/user.rs, crates/quark/src/traits/users/user.rs
Closes #247
For https://github.com/revoltchat/rfcs/pull/3
=> feat: add discriminator and display name fields

crates/delta/src/routes/servers/roles_delete.rs
=> fix: incorrect owner rank when deleting a role

crates/core/database/src/models/admin_migrations/ops/mongodb/scripts.rs, crates/core/database/src/models/channel_webhooks/model.rs, crates/core/database/src/util/bridge/v0.rs, crates/core/models/src/v0/channel_webhooks.rs, crates/core/permissions/src/models/channel.rs, crates/delta/src/routes/channels/webhook_create.rs, crates/delta/src/routes/webhooks/webhook_edit.rs, crates/delta/src/routes/webhooks/webhook_edit_token.rs, crates/delta/src/routes/webhooks/webhook_execute.rs, crates/quark/src/impl/generic/channels/message.rs, crates/quark/src/permissions/defn/permission.rs
=> feat: add webhook permissions

crates/delta/src/routes/users/find_mutual.rs
=> fix: allow fetching mutuals for bots

Cargo.toml, crates/bonfire/Cargo.toml, crates/bonfire/src/websocket.rs
Log errors from failed pub/sub messages.
=> chore: Log errors from failed pub/sub messages

crates/core/database/src/events/client.rs, crates/core/database/src/models/emojis/ops/mongodb.rs, crates/core/database/src/models/server_members/model.rs, crates/quark/src/events/client.rs, crates/quark/src/events/impl.rs, crates/quark/src/impl/generic/servers/server.rs
=> fix: add emojis to ServerCreate event

crates/delta/src/routes/customisation/emoji_create.rs
funny message goes here
closes #295
=> Disallow servers to exceed instance's max emoji limit by one

Cargo.lock, crates/bonfire/Cargo.toml, crates/bonfire/src/main.rs, crates/bonfire/src/websocket.rs
Use fred.rs for bonfires redis connections instead of redis-rs
https://github.com/aembke/fred.rs
Fixes the random disconnects from bonfire when redis-rs fails to parse a message.
=> fix(bonfire): random disconnects from redis

crates/delta/src/routes/servers/member_fetch.rs, crates/delta/src/routes/servers/mod.rs, crates/delta/src/routes/servers/roles_fetch.rs, crates/quark/src/impl/dummy/servers/server_member.rs, crates/quark/src/impl/generic/servers/server_member.rs, crates/quark/src/impl/mongo/servers/server_member.rs, crates/quark/src/models/servers/server_member.rs, crates/quark/src/traits/servers/server_member.rs, crates/quark/src/util/ref.rs
=> Member fetching with roles 

crates/quark/src/impl/generic/servers/server_member.rs, crates/quark/src/impl/mongo/servers/server_member.rs, crates/quark/src/models/servers/server_member.rs
=> fix(delta): Make MemberResponse an untagged enum and only include member roles 

crates/core/database/src/util/bridge/v0.rs, crates/core/models/Cargo.toml, crates/core/models/src/v0/messages.rs
=> fix(core/models): use IndexMap for reactions

crates/delta/src/util/ratelimiter.rs
=> fix(delta): set ratelimit headers on 429 responses

.github/workflows/rust.yaml
=> fix(ci): build API then run in background to prevent timeout

.github/workflows/rust.yaml
=> fix(ci): only start run command in background

crates/bonfire/src/websocket.rs
=> chore(bonfire): log errors from websocket stream

.github/workflows/rust.yaml
I was wondering why the API hand regenerated so I took a look at the latest commit's jobs and noticed that these were being skipped - looks like these were missed in the branch rename.
=> fix(ci): remnants from branch rename

crates/core/models/src/v0/embeds.rs
See https://github.com/revoltchat/january/pull/41
=> chore: applemusic option for special embed

crates/core/database/src/models/messages/ops/mongodb.rs
Was causing a full collection scan as well as never returning any matches. Which was breaking the bulk message delete route
=> fix(core): fix _id typo

crates/delta/src/routes/channels/channel_delete.rs, crates/delta/src/routes/invites/invite_fetch.rs, crates/delta/src/util/test.rs
Add tests for the invite/fetch route as part of #282.
=> test: Add tests for invite/fetch

.github/workflows/docker.yaml
Just one line missing to make the container creation happen
Related to eb5f5f91cdd2eb37b4b99ed66b90887b8c6f4895
---------
Just asking docker to make the crond container works. I'm not able to test this yaml change, as my github username has a capital letter, which results in other errors when I run the workflow on my account. 
> buildx failed with: ERROR: invalid tag "ghcr.io/Docteh/base:latest": repository name must be lowercase
=> fix: Actually create crond container in github workflow
